### PR TITLE
Warn if project directory or workshop definition does not exist

### PR DESCRIPTION
**Pull request by jonathan-conder**
# Description

Adds warnings in addition to status for `missing-file` and `missing-project` checks.

# Self-review quick check

 * [x] Make decisions that cost a lot to reverse explicit in the PR description.
 * [x] Avoid nested conditions.
 * [x] Delete dead code and redundant comments.
 * [x] Normalise symmetries by sticking to doing identical things identically. 
 ```
 // one way to handle errors
 if err := f(); err != nil {
    ...
 }
 
 // one way to handle multiple returns
 val, err := f()
 if err != nil {
    ...
 }
 ...
 ```
 * [x] Check that coupled code elements, files, and directories are adjacent. For example, test data is stored as close as possible to a test.
 * [x] Put variable declaration and initialisation together.
 * [x] Divide large expressions into digestable and self-explanatory ones. Use multiple variables if required.
 * [x] Put a blank line between two logically different chunks of code.

### CODE REVIEW

**Comment by jonathan-conder** [comment]
The documentation checks failed initially. Think it was a transient network error but you might want to double-check

**Comment by akcano** [comment]
@jonathan-conder I can't see anything on the logs; the PR scope also doesn't affect anything these checks, well, check.

**Comment by jonathan-conder** [comment]
I reran it already, the original logs are here: https://github.com/canonical/workshop/actions/runs/11138115693/job/30952613787?pr=178

**Review by dmitry-lyfar — APPROVED** [review]

**Comment by dmitry-lyfar** [comment]
@jonathan-conder looks pretty good, merging it. @akcano it fails with `https://discourse.canonical.com/c/engineering/sdk/34`, not sure how it accesses a private link, but that seems due to the Discourse outage which happens at times, so transient.

**Comment by akcano** [comment]
@dmitry-lyfar the link check normally bumps into a login gateway redirect, which is legit in its opinion. If Discourse is down, though, no redirects occur, hence the transient failure.

**Pull request merged**
