### PR TITLE
Update installation info, improve layout

### PR DESCRIPTION
**Pull request by akcano**

### CODE REVIEW

**Comment by dmitry-lyfar** [comment]
@akcano we should consider not highlighting the product name at all and rely on the common sense that one can tell which is which from the context and from the spelling. I cannot help getting distracted by either bold or italic; perhaps, it is worth highlighting on the first occurrence.

**Comment by akcano** [comment]
> @akcano we should consider not highlighting the product name at all and rely on the common sense that one can tell which is which from the context and from the spelling. I cannot help getting distracted by either bold or italic; perhaps, it is worth highlighting on the first occurrence.

Regular font is absolutely OK; if you remember, we started highlighting product names to distinguish Workshop from a workshop better, so if this is getting counterproductive, the highlight needs to go. However, I'm leaving the semantic markup in place to avoid losing context.

**Review by dmitry-lyfar — APPROVED** [review]

**Comment by dmitry-lyfar** [comment]
@akcano there are some link checks failing, but overall looks good!

**Comment by akcano** [comment]
that's transient but I want to investigate, please don't merge yet

**Pull request merged**
